export const USE_CASES = Object.freeze([
  {
    id:'labra',
    name:'LABRA-AGU',
    subtitle:'Recuperação de ativos · sistema pericial de IA',
    repo:'https://github.com/JoseRFJuniorLLMs/LABRA-AGU',
    snapshot:'9b5d9bcada759e23e12c2d995be17dca6e42a8e1',
    runtime:'http://127.0.0.1:8770',
    runtimeLabel:'Agente investigativo original',
    accent:'cyan',
    capabilities:['Alertas de Fraude','Mapa de Relações','Emitir Diretriz','Heraclitus Explorer','Agente investigativo sobre o log real'],
    sourceUi:'dashboard/src/App.jsx + serve.py',
  },
  {
    id:'aeb',
    name:'AEB-STREAM',
    subtitle:'Operação espacial · órbita, telemetria e anomalias',
    repo:'https://github.com/JoseRFJuniorLLMs/AEB',
    snapshot:'b8e9de466e9071a4b1c490a4faabb249dda36e9b',
    runtime:'http://127.0.0.1:7480',
    runtimeLabel:'Dashboard orbital original',
    accent:'space',
    capabilities:['Globo 3D','Satélites brasileiros','Estações terrenas','Telemetria','Anomalias ACT-R'],
    sourceUi:'dashboard.py',
  },
  {
    id:'cgee',
    name:'CGEE',
    subtitle:'Integridade orçamentária · SIOP, AS OF, WHY e Merkle',
    repo:'https://github.com/JoseRFJuniorLLMs/CGEE',
    snapshot:'31951717036bd39d9bc898a80686f3907ffd8699',
    runtime:'http://127.0.0.1:8000',
    runtimeLabel:'Painel de integridade original',
    accent:'budget',
    capabilities:['Linha do tempo viva','Heatmap estilo GitHub','Exercícios','WHY por portaria','Verificação do log'],
    sourceUi:'painel.html + painel_server.py',
  },
  {
    id:'frd',
    name:'SPEC-FRD-001 v2.0',
    subtitle:'Detecção, Triangulação e Evidência de Riscos de Integridade Pública',
    repo:'docs/SPEC-FRD-001 v2.0 — Detecção, Triangulação e Evidência de Riscos de Integridade Pública.md',
    snapshot:'2026.09.17-v2.0',
    runtime:'http://127.0.0.1:9337/frd-api',
    runtimeLabel:'Console Pericial de Integridade',
    accent:'fraud',
    capabilities:['Dashboard Executivo','Fila de Triagem','Grafo Temporal Multi-Hop','Time Travel (AS OF LSN)','Dossiê Probatório Merkle','Decisão Humana & Audit Trail'],
    sourceUi:'SPEC-FRD-001 v2.0 / FrdCase.js',
  },
]);

export const USE_CASE_BY_ID = new Map(USE_CASES.map(item => [item.id,item]));
