const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '..');
const read = p => fs.readFileSync(path.join(root,p),'utf8');
const app=read('js/app.js'), nav=read('js/components/Navigation.js'), time=read('js/components/TimeMachine.js');
const agent=read('js/components/AgentBlackBox.js'), publicData=read('js/components/PublicData.js');
const why=read('js/components/CausalInvestigation.js'), replay=read('js/components/AttackReplay.js');
const ai=read('js/components/ForensicAI.js'), comp=read('js/components/CompliancePanel.js');
const api=read('js/api.js'), index=read('index.html');
assert(app.includes('PlatformOverview.render()'));
assert(app.includes('PublicData.render()'));
assert(app.includes('AgentBlackBox.render()'));
assert(nav.indexOf('Visão geral') < nav.indexOf('Sentinel / SOC'));
assert(nav.includes('Agent Black Box'));
assert(!time.includes('gerarEventosSinteticos'));
assert(!time.includes('EVENTOS_FALBACK'));
assert(!replay.includes('INC-2026-0012'));
assert(!why.includes('Servidor caiu'));
assert(!ai.includes('db.verify ✓'));
assert(!comp.includes('todos os segmentos íntegros'));
assert(agent.includes('/api/v1/agent/status'));
assert(agent.includes('/api/v1/agent/runs'));
assert(publicData.includes('EXTERNA · NÃO SELADA'));
assert(!api.includes('sessionStorage'));
assert(!api.includes("localStorage.setItem('hera_auth'"));
assert(index.includes('css/platform.css'));
assert(index.includes('js/app.js'));
console.log('Dashboard contracts OK: platform-first, no synthetic forensic claims, Agent/Public surfaces wired.');
