const REPO='https://github.com/JoseRFJuniorLLMs/AEB';
const SNAPSHOT='b8e9de466e9071a4b1c490a4faabb249dda36e9b';
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=p=>`${REPO}/blob/${SNAPSHOT}/${p}`;
const SATS=[['47699','AMAZONIA-1'],['44883','CBERS-4A'],['40336','CBERS-4'],['25504','SCD-2'],['22490','SCD-1'],['43226','SGDC-1']];
const STATIONS=[['Cuiabá (INPE)',-15.555,-56.069],['Cachoeira Paulista (INPE)',-22.689,-45.005],['Alcântara (CLA)',-2.373,-44.396],['Barreira do Inferno (Natal)',-5.924,-35.161]];
const FILES=['README.md','pipeline.py','consulta.py','main.py','stream.py','seed_demo.py','dashboard.py','requirements.txt','agent/orbit.py','agent/graph.py','agent/act_r.py','agent/anomalias.py','assets/dasboard.png','assets/earth.jpg','assets/topo.png','assets/sky.png','assets/globe.gl.min.js'];
const fileGrid=()=>FILES.map(p=>`<a href="${link(p)}" target="_blank" rel="noopener noreferrer"><span>${esc(p)}</span><span>↗</span></a>`).join('');
const latestByCat=data=>{const m=new Map();for(const r of data?.estados||[]){const k=String(r.catnr??'');const p=m.get(k);if(!p||Number(r.lsn||0)>Number(p.lsn||0))m.set(k,r);}return m;};

export const AebStreamCase={
 data:null,
 render(){return `<section id="aeb" class="aeb-case aeb-origin-case">
  <div class="origin-case-header aeb-origin-header"><div><span class="origin-case-kicker">CASOS / AEB-STREAM</span><h2>🛰 AEB-STREAM</h2><p>Operação espacial, órbita, telemetria e anomalias sobre HeraclitusDB</p></div><div class="origin-case-status"><span id="aeb-runtime">runtime não sondado</span><span id="aeb-head">HEAD —</span><span>snapshot ${SNAPSHOT.slice(0,10)}</span></div></div>
  <div class="origin-truth-banner"><strong>Projeto fonte preservado.</strong> O primeiro painel é o <code>dashboard.py</code> original executado em <code>:7480</code>, incluindo globo 3D, satélites, antenas, contactos, sparklines e anomalias. TLE/órbita usam CelesTrak/SGP4; telemetria térmica/elétrica do PoC continua simulada.</div>
  <nav class="origin-tabs aeb-origin-tabs"><button class="active" data-aeb-view="original">Painel orbital original</button><button data-aeb-view="runtime">Dados do runtime</button><button data-aeb-view="architecture">Arquitetura</button><button data-aeb-view="project">Projeto fonte</button></nav>
  <div class="aeb-origin-view active" data-aeb-origin="original"><div class="origin-runtime-head"><div><h3>Dashboard AEB original</h3><p>Exatamente a aplicação web servida por <code>dashboard.py</code>. Se a moldura estiver vazia, inicie o runtime.</p></div><code>cd ~/AEB && python3 dashboard.py</code></div><iframe class="origin-runtime-frame aeb-runtime-frame" title="AEB-STREAM dashboard original" src="http://127.0.0.1:7480" sandbox="allow-scripts allow-same-origin"></iframe></div>
  <div class="aeb-origin-view" data-aeb-origin="runtime"><div class="origin-demo-label">LEITURA DIRETA DE GET /AEB-API/DATA</div><div class="aeb-live-kpis"><article><span>Satélites</span><strong id="aeb-sats">—</strong></article><article><span>Leituras</span><strong id="aeb-states">—</strong></article><article><span>Anomalias</span><strong id="aeb-anoms">—</strong></article><article><span>Estações modeladas</span><strong>${STATIONS.length}</strong></article></div><button class="btn" id="aeb-refresh" type="button">Atualizar runtime</button><div class="table-wrap"><table><thead><tr><th>Satélite</th><th>Lat</th><th>Lon</th><th>Altitude</th><th>Bateria</th><th>Painéis</th><th>Iluminação</th></tr></thead><tbody id="aeb-live-sats"><tr><td colspan="7" class="vazio">Runtime ainda não consultado.</td></tr></tbody></table></div><div class="aeb-station-grid">${STATIONS.map(([n,lat,lon])=>`<article><strong>📡 ${esc(n)}</strong><span>${lat.toFixed(3)}°, ${lon.toFixed(3)}°</span></article>`).join('')}</div></div>
  <div class="aeb-origin-view" data-aeb-origin="architecture"><div class="aeb-source-flow"><article><span>01</span><strong>CelesTrak / TLE</strong><p>Elementos orbitais públicos.</p></article><b>→</b><article><span>02</span><strong>SGP4 + geodésia</strong><p>Posição, latitude, longitude e altitude.</p></article><b>→</b><article><span>03</span><strong>H × S × E</strong><p>Geometria orbital, métricas e hierarquia.</p></article><b>→</b><article><span>04</span><strong>HeraclitusDB</strong><p>OrbitState append-only, LSN e parents.</p></article><b>→</b><article><span>05</span><strong>Cérebro</strong><p>SatGraph, ACT-R e detectores.</p></article></div><div class="aeb-anomaly-grid">${[['TERMICA','Temperatura fora da janela'],['TERMICA_SALTO','Salto térmico'],['ENERGIA','Tensão solar baixa'],['ORBITA','Desvio de altitude']].map(([c,d])=>`<article><code>${c}</code><p>${d}</p></article>`).join('')}</div><div class="origin-truth-banner"><strong>Fronteira operacional:</strong> órbita/TLE podem ser reais; temperatura e tensão só devem ser tratadas como operação real depois de substituir <code>simular_telemetria()</code> por feed de missão.</div></div>
  <div class="aeb-origin-view" data-aeb-origin="project"><div class="origin-project-head"><div><h3>Projeto originário completo</h3><p>Snapshot <code>${SNAPSHOT}</code>.</p></div><a class="btn" href="${REPO}" target="_blank" rel="noopener noreferrer">Abrir GitHub ↗</a></div><div class="origin-file-grid">${fileGrid()}</div></div>
 </section>`},
 init(){document.querySelectorAll('[data-aeb-view]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-aeb-view]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('[data-aeb-origin]').forEach(x=>x.classList.toggle('active',x.dataset.aebOrigin===b.dataset.aebView));if(b.dataset.aebView==='runtime')this.refresh();}));document.getElementById('aeb-refresh')?.addEventListener('click',()=>this.refresh());},
 async refresh(){const runtime=document.getElementById('aeb-runtime');try{const r=await fetch('/aeb-api/data',{cache:'no-store'});if(!r.ok)throw new Error();this.data=await r.json();runtime.textContent='runtime online';document.getElementById('aeb-head').textContent=`HEAD ${this.data.head??'—'}`;document.getElementById('aeb-sats').textContent=(this.data.satelites||[]).length;document.getElementById('aeb-states').textContent=(this.data.estados||[]).length;document.getElementById('aeb-anoms').textContent=(this.data.anomalias||[]).length;const latest=latestByCat(this.data),defs=new Map((this.data.satelites||[]).map(s=>[String(s.catnr),s]));document.getElementById('aeb-live-sats').innerHTML=SATS.map(([cat,name])=>{const e=latest.get(cat),s=defs.get(cat);return `<tr><td><strong>${esc(s?.nome||name)}</strong><small>NORAD ${cat}</small></td><td>${e?.lat==null?'—':Number(e.lat).toFixed(2)+'°'}</td><td>${e?.lon==null?'—':Number(e.lon).toFixed(2)+'°'}</td><td>${e?.alt==null?'—':Number(e.alt).toFixed(1)+' km'}</td><td>${e?.temp==null?'—':Number(e.temp).toFixed(1)+' °C'}</td><td>${e?.volt==null?'—':Number(e.volt).toFixed(1)+' V'}</td><td>${e?.eclipse?'eclipse':'sol'}</td></tr>`;}).join('');}catch{runtime.textContent='runtime offline';document.getElementById('aeb-live-sats').innerHTML='<tr><td colspan="7" class="vazio">AEB local indisponível em 127.0.0.1:7480.</td></tr>';}}
};
