const REPO='https://github.com/JoseRFJuniorLLMs/CGEE';
const SNAPSHOT='31951717036bd39d9bc898a80686f3907ffd8699';
const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=p=>`${REPO}/blob/${SNAPSHOT}/${p}`;
const FILES=['README.md','SPEC.md','app.py','ingest_amostra.py','main.py','painel.html','painel_server.py','img/0.png','img/1.png','img/2.png','img/3.png','img/4.png','img/5.png','img/6.png'];
const fileGrid=()=>FILES.map(p=>`<a href="${link(p)}" target="_blank" rel="noopener noreferrer"><span>${esc(p)}</span><span>↗</span></a>`).join('');
const toDate=v=>{const d=new Date(String(v||'').replace(' ','T'));return Number.isNaN(d.getTime())?null:d;};
const lsnOf=e=>Number(e?.lsn??e?.at_lsn??0);
const attr=e=>e?.attrs||e?.attributes||e||{};
const eventDate=e=>toDate(attr(e).data_oficial||e?.timestamp||e?.created_at||e?.observed_at);
const eventValue=e=>Number(attr(e).valor||0);
const actionOf=e=>attr(e).action_id||attr(e).portaria||e?.action_id||'—';

export const CgeeCase={
 events:[],cursor:0,timer:null,
 render(){return `<section id="cgee" class="cgee-case cgee-origin-case">
  <div class="origin-case-header cgee-origin-header"><div><span class="origin-case-kicker">CASOS / CGEE</span><h2>Integridade Orçamentária</h2><p>SIOP + HeraclitusDB · AS OF, WHY, Merkle e reconstituição histórica</p></div><div class="origin-case-status"><span id="cgee-runtime">runtime não sondado</span><span id="cgee-count">0 eventos</span><span>snapshot ${SNAPSHOT.slice(0,10)}</span></div></div>
  <div class="origin-truth-banner"><strong>Projeto fonte preservado.</strong> O painel original em <code>painel.html</code> é mostrado dentro do caso quando <code>painel_server.py</code> está ativo. A cópia nativa abaixo usa somente eventos reais do runtime e não ativa o fallback sintético do HTML original.</div>
  <nav class="origin-tabs cgee-origin-tabs"><button class="active" data-cgee-view="original">Painel original</button><button data-cgee-view="timeline">Linha do tempo viva</button><button data-cgee-view="why">WHY & integridade</button><button data-cgee-view="ingest">Ingestão SIOP</button><button data-cgee-view="project">Projeto fonte</button></nav>
  <div class="cgee-origin-view active" data-cgee-origin="original"><div class="origin-runtime-head"><div><h3>Painel CGEE original</h3><p>Interface real do projeto, com seletor de exercício, timeline, heatmap, WHY e escudo de integridade.</p></div><code>cd ~/CGEE && python3 painel_server.py</code></div><iframe class="origin-runtime-frame cgee-runtime-frame" title="CGEE painel original" src="http://127.0.0.1:8000" sandbox="allow-scripts allow-same-origin"></iframe></div>
  <div class="cgee-origin-view" data-cgee-origin="timeline"><div class="origin-demo-label">TIMELINE NATIVA · SOMENTE EVENTOS REAIS DO RUNTIME CGEE</div><div class="cgee-native-toolbar"><button class="btn" id="cgee-load" type="button">Carregar eventos</button><button class="btn ghost" id="cgee-play" type="button">▶ Reproduzir</button><label>Exercício<select id="cgee-year"><option value="">Todos</option></select></label><div><span>AS OF LSN</span><strong id="cgee-asof">—</strong></div></div><input id="cgee-slider" type="range" min="0" max="0" value="0" class="cgee-native-slider"><div class="cgee-progress-grid"><article><span>Eventos acumulados</span><strong id="cgee-progress-events">0 / 0</strong><div class="cgee-native-progress"><i id="cgee-progress-events-bar"></i></div></article><article><span>Volume absoluto percorrido</span><strong id="cgee-progress-value">R$ 0,00</strong><div class="cgee-native-progress"><i id="cgee-progress-value-bar"></i></div></article></div><div id="cgee-heatmap" class="cgee-native-heatmap"></div><div class="table-wrap"><table><thead><tr><th>LSN</th><th>Data</th><th>Portaria / ação</th><th>Órgão</th><th>Tipo</th><th>Valor</th></tr></thead><tbody id="cgee-rows"><tr><td colspan="6" class="vazio">Carregue o runtime CGEE.</td></tr></tbody></table></div></div>
  <div class="cgee-origin-view" data-cgee-origin="why"><div class="cgee-why-grid"><article><h3>WHY por action_id</h3><p>O snapshot atual localiza a alteração pelo identificador de ação/portaria.</p><div class="cgee-query"><input id="cgee-why-input" type="text" placeholder="action_id / portaria"><button class="btn" id="cgee-why-button" type="button">Investigar WHY</button></div><pre id="cgee-why-result" class="json-view">Nenhuma consulta executada.</pre></article><article><h3>Verificação do log</h3><p>Executa a verificação real exposta pelo runtime do projeto.</p><button class="btn" id="cgee-verify" type="button">Verificar agora</button><pre id="cgee-verify-result" class="json-view">Ainda não verificado.</pre></article></div></div>
  <div class="cgee-origin-view" data-cgee-origin="ingest"><div class="cgee-source-flow"><article><span>01</span><strong>CSV SIOP</strong><p>Créditos, instrumentos legais, órgãos, ações e valores.</p></article><b>→</b><article><span>02</span><strong>ingest_amostra.py</strong><p><code>val_acrescimo - val_reducao</code>.</p></article><b>→</b><article><span>03</span><strong>Ordenação cronológica</strong><p>Data oficial do instrumento legal.</p></article><b>→</b><article><span>04</span><strong>AlteracaoOrcamentaria</strong><p>Append no HeraclitusDB e LSN.</p></article><b>→</b><article><span>05</span><strong>AS OF / WHY / verify</strong><p>Reconstituição e integridade.</p></article></div></div>
  <div class="cgee-origin-view" data-cgee-origin="project"><div class="origin-project-head"><div><h3>Projeto originário completo</h3><p>Snapshot <code>${SNAPSHOT}</code>.</p></div><a class="btn" href="${REPO}" target="_blank" rel="noopener noreferrer">Abrir GitHub ↗</a></div><div class="origin-file-grid">${fileGrid()}</div></div>
 </section>`},
 init(){document.querySelectorAll('[data-cgee-view]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-cgee-view]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('[data-cgee-origin]').forEach(x=>x.classList.toggle('active',x.dataset.cgeeOrigin===b.dataset.cgeeView));if(b.dataset.cgeeView==='timeline')this.load();}));document.getElementById('cgee-load')?.addEventListener('click',()=>this.load());document.getElementById('cgee-play')?.addEventListener('click',()=>this.togglePlay());document.getElementById('cgee-slider')?.addEventListener('input',e=>{this.pause();this.cursor=Number(e.target.value);this.paint();});document.getElementById('cgee-year')?.addEventListener('change',()=>{this.pause();this.cursor=Math.max(0,this.filtered().length-1);this.paint(true);});document.getElementById('cgee-why-button')?.addEventListener('click',()=>this.why());document.getElementById('cgee-verify')?.addEventListener('click',()=>this.verify());},
 filtered(){const year=document.getElementById('cgee-year')?.value;return this.events.filter(e=>!year||String(eventDate(e)?.getFullYear())===year);},
 async load(){const runtime=document.getElementById('cgee-runtime');try{const r=await fetch('/cgee-api/timeline?limit=5000',{cache:'no-store'});if(!r.ok)throw new Error();const d=await r.json();this.events=(Array.isArray(d)?d:(d.events||d.items||[])).filter(e=>eventDate(e)).sort((a,b)=>eventDate(a)-eventDate(b));runtime.textContent='runtime online';document.getElementById('cgee-count').textContent=`${this.events.length.toLocaleString('pt-BR')} eventos`;const years=[...new Set(this.events.map(e=>eventDate(e).getFullYear()))].sort();const sel=document.getElementById('cgee-year');sel.innerHTML='<option value="">Todos</option>'+years.map(y=>`<option>${y}</option>`).join('');this.cursor=Math.max(0,this.filtered().length-1);this.paint(true);}catch{runtime.textContent='runtime offline';document.getElementById('cgee-rows').innerHTML='<tr><td colspan="6" class="vazio">CGEE local indisponível em 127.0.0.1:8000.</td></tr>';document.getElementById('cgee-heatmap').innerHTML='<div class="temporal-empty">Sem runtime. Nenhum dado sintético foi criado.</div>';}}
 ,paint(resetSlider=false){const list=this.filtered(),slider=document.getElementById('cgee-slider');if(!list.length){slider.max='0';slider.value='0';return;}this.cursor=Math.max(0,Math.min(this.cursor,list.length-1));if(resetSlider){slider.max=String(list.length-1);slider.value=String(this.cursor);}else slider.value=String(this.cursor);const current=list[this.cursor],visible=list.slice(0,this.cursor+1),totalAbs=list.reduce((s,e)=>s+Math.abs(eventValue(e)),0)||1,visAbs=visible.reduce((s,e)=>s+Math.abs(eventValue(e)),0),pct=((this.cursor+1)/list.length)*100;document.getElementById('cgee-asof').textContent=lsnOf(current).toLocaleString('pt-BR');document.getElementById('cgee-progress-events').textContent=`${this.cursor+1} / ${list.length}`;document.getElementById('cgee-progress-events-bar').style.width=`${pct}%`;document.getElementById('cgee-progress-value').textContent=visAbs.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});document.getElementById('cgee-progress-value-bar').style.width=`${Math.min(100,(visAbs/totalAbs)*100)}%`;this.heatmap(visible,list);document.getElementById('cgee-rows').innerHTML=visible.slice(-200).reverse().map(e=>{const a=attr(e),d=eventDate(e);return `<tr><td class="mono">${lsnOf(e)||'—'}</td><td>${d.toISOString().slice(0,10)}</td><td>${esc(actionOf(e))}</td><td>${esc(a.orgao)}</td><td>${esc(a.tipo_alteracao||e.kind)}</td><td>${eventValue(e).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</td></tr>`;}).join('');},
 heatmap(visible,all){const out=document.getElementById('cgee-heatmap'),counts=new Map();for(const e of visible){const k=eventDate(e).toISOString().slice(0,10);counts.set(k,(counts.get(k)||0)+1);}const end=eventDate(all.at(-1)),start=new Date(end.getTime()-363*86400000),max=Math.max(...counts.values(),1);out.innerHTML='';for(let i=0;i<364;i++){const d=new Date(start.getTime()+i*86400000),k=d.toISOString().slice(0,10),n=counts.get(k)||0,lv=n?Math.max(1,Math.min(4,Math.ceil((n/max)*4))):0;const s=document.createElement('span');s.className=`cgee-day level-${lv}`;s.title=`${k}: ${n} evento(s)`;out.append(s);}},
 togglePlay(){if(this.timer){this.pause();return;}const list=this.filtered();if(!list.length)return;if(this.cursor>=list.length-1)this.cursor=0;document.getElementById('cgee-play').textContent='⏸ Pausar';this.timer=setInterval(()=>{this.cursor=Math.min(list.length-1,this.cursor+1);this.paint();if(this.cursor>=list.length-1)this.pause();},160);},pause(){if(this.timer)clearInterval(this.timer);this.timer=null;const b=document.getElementById('cgee-play');if(b)b.textContent='▶ Reproduzir';},
 async why(){const q=document.getElementById('cgee-why-input').value.trim(),out=document.getElementById('cgee-why-result');if(!q){out.textContent='Informe um action_id / portaria.';return;}out.textContent='Consultando…';try{const r=await fetch(`/cgee-api/why?portaria=${encodeURIComponent(q)}`,{cache:'no-store'});const d=await r.json();out.textContent=JSON.stringify(d,null,2);}catch{out.textContent='Runtime CGEE indisponível.';}},
 async verify(){const out=document.getElementById('cgee-verify-result');out.textContent='Verificando…';try{const r=await fetch('/cgee-api/verify',{cache:'no-store'}),d=await r.json();out.textContent=JSON.stringify(d,null,2);}catch{out.textContent='Runtime CGEE indisponível.';}}
};
