import { API, explicarFalha } from '../api.js';
export const Modos={
  barra(){return '';},
  render(){return `<section id="auditor"><div class="secttl"><h2>Auditoria</h2><span class="tag">proveniência · determinismo · integridade</span></div><p class="sub">Responde com medições: integridade, replay determinístico, fontes e mapa de atributos. Não transforma configuração técnica em homologação de TCU/CGU/ANPD.</p><div class="grid k4"><div class="kpi" id="au-integ-card"><div class="lb">Integridade</div><div class="v small-v" id="au-integ">não verificada</div><div class="acao"><button class="btn" id="au-verify">Verificar</button></div></div><div class="kpi"><div class="lb">Fontes</div><div class="v" id="au-fontes">—</div></div><div class="kpi"><div class="lb">Campos indexados</div><div class="v" id="au-campos">—</div></div><div class="kpi"><div class="lb">Head LSN</div><div class="v" id="au-head">—</div></div></div><div class="card"><h3>Estado reprodutível</h3><div id="au-replay" class="vazio-block">Ainda não consultado.</div><div class="acao"><button class="btn ghost" id="au-replay-btn">Consultar replay</button></div></div></section>`},
  init(){document.getElementById('au-verify').onclick=()=>this.verify();document.getElementById('au-replay-btn').onclick=()=>this.replay();this.summary();},
  async summary(){const [s,f,a]=await Promise.all([API.stats(),API.get('/fontes',{ms:20000}),API.get('/atributos',{ms:20000})]);if(s.ok)document.getElementById('au-head').textContent=Number(s.dados.head).toLocaleString('pt-BR');if(f.ok)document.getElementById('au-fontes').textContent=(f.dados.fontes||[]).length.toLocaleString('pt-BR');if(a.ok)document.getElementById('au-campos').textContent=(a.dados.campos||[]).length.toLocaleString('pt-BR');},
  async verify(){const e=document.getElementById('au-integ'),c=document.getElementById('au-integ-card');e.textContent='verificando…';const r=await API.verify();if(!r.ok){e.textContent='não verificada';c.className='kpi';return;}const d=r.dados||{},ok=d.ok===true||d.valid===true||d.verified===true||d.status==='VERIFIED'||d.status==='ok';e.textContent=ok?'íntegra':'FALHA';c.className='kpi '+(ok?'ok':'bad');},
  async replay(){const out=document.getElementById('au-replay');out.textContent='Consultando…';const r=await API.get('/replay',{ms:60000});if(!r.ok){out.textContent=explicarFalha(r.falha,r.estado).longo;return;}const p=document.createElement('pre');p.className='json-view';p.textContent=JSON.stringify(r.dados,null,2);out.replaceChildren(p);}
};
