import { API, explicarFalha } from '../api.js';
const esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rawTime=r=>r?.observed_at??r?.timestamp??r?.created_at??r?.time??r?.ts??r?.observed_at_unix_ms??r?.t_ms;
const toMs=v=>{if(typeof v==='string'){const n=Date.parse(v);return Number.isFinite(n)?n:null;}if(Number.isFinite(v)){if(v>1e17)return Math.floor(v/1e6);if(v>1e14)return Math.floor(v/1e3);if(v>1e11)return v;if(v>1e9)return v*1000;}return null;};
const lsnOf=r=>r?.lsn??r?.at_lsn??r?.last_seen_lsn??r?.integrity?.lsn??null;
const dayKey=ms=>new Date(ms).toISOString().slice(0,10);

export const TimeMachine={
  rows:[],entries:[],cursor:0,timer:null,active:false,head:null,speed:1,
  render(){return `<section id="time" class="temporal-workbench"><div class="secttl"><h2>Temporal Reconstruction Workbench</h2><span class="tag">dados reais · sem fallback sintético</span></div>
    <p class="sub">A identidade temporal original voltou: barra temporal, replay, duas barras de progresso e mapa de atividade estilo GitHub. Tudo é reconstruído somente a partir dos eventos retornados pelo HeraclitusDB.</p>
    <div id="tl-notice" class="aviso" hidden></div>

    <div class="temporal-spine-r9 card">
      <div class="temporal-modes"><span class="temporal-eyebrow">BARRA TEMPORAL GLOBAL</span><div class="temporal-mode-buttons"><button class="temporal-mode active" id="tl-mode-live" type="button">● LIVE <small id="tl-head">HEAD —</small></button><button class="temporal-mode" id="tl-mode-asof" type="button">⏱ AS OF LSN</button><button class="temporal-mode" id="tl-mode-compare" type="button">⇄ COMPARE A ↔ B</button><button class="temporal-mode" id="tl-mode-replay" type="button">▶ REPLAY</button></div></div>
      <div class="temporal-controls"><button class="temporal-step" id="tl-step-back" type="button" title="Voltar um evento">◀</button><button class="temporal-play" id="tl-play" type="button">▶</button><button class="temporal-step" id="tl-step-fwd" type="button" title="Avançar um evento">▶</button><label>VELOCIDADE<select id="tl-speed"><option value="1">1x</option><option value="5">5x</option><option value="25">25x</option><option value="100">MAX</option></select></label><button class="btn" id="tl-load" type="button">Carregar eventos reais</button><span class="pill b">/security/events</span></div>
      <div class="temporal-cursor"><input type="range" id="tl-cursor" min="0" max="0" value="0" aria-label="Cursor temporal"><div class="temporal-cursor-readout"><strong id="tl-cursor-lsn">LSN —</strong><span id="tl-cursor-date">Sem eventos carregados</span></div></div>
      <div class="temporal-progress-grid"><article><div><span>Eventos percorridos</span><strong id="tl-progress-events">0 / 0</strong></div><div class="temporal-progress"><i id="tl-progress-events-bar"></i></div></article><article><div><span>Intervalo LSN percorrido</span><strong id="tl-progress-lsn">0%</strong></div><div class="temporal-progress lsn"><i id="tl-progress-lsn-bar"></i></div></article></div>
    </div>

    <div class="card temporal-activity-card"><div class="temporal-card-head"><div><span class="temporal-eyebrow">52 SEMANAS</span><h3>Temporal Activity Map</h3><p>Densidade diária no log, no mesmo espírito do gráfico de contribuições do GitHub.</p></div><div class="temporal-legend"><span>menos</span><i class="level-0"></i><i class="level-1"></i><i class="level-2"></i><i class="level-3"></i><i class="level-4"></i><span>mais</span></div></div><div id="tl-calendar" class="temporal-github-grid" aria-label="Mapa temporal de atividade"></div></div>

    <div class="card"><div class="temporal-card-head"><div><h3>Eventos até o cursor</h3><p id="tl-count">Nenhum dado carregado.</p></div><button class="btn ghost" id="tl-jump-head" type="button">Voltar ao HEAD</button></div><div class="table-wrap"><table><thead><tr><th>Data UTC</th><th>LSN</th><th>Fonte</th><th>Tipo</th><th>Evidência</th></tr></thead><tbody id="tl-body"><tr><td colspan="5" class="vazio">Carregue os eventos reais do Core.</td></tr></tbody></table></div></div>
  </section>`},
  init(){
    document.getElementById('tl-load')?.addEventListener('click',()=>this.load());document.getElementById('tl-play')?.addEventListener('click',()=>this.togglePlay());document.getElementById('tl-step-back')?.addEventListener('click',()=>this.step(-1));document.getElementById('tl-step-fwd')?.addEventListener('click',()=>this.step(1));document.getElementById('tl-jump-head')?.addEventListener('click',()=>this.jumpHead());document.getElementById('tl-cursor')?.addEventListener('input',e=>{this.pause();this.cursor=Number(e.target.value);this.paint();this.setMode('asof');});document.getElementById('tl-speed')?.addEventListener('change',e=>this.speed=Number(e.target.value)||1);document.getElementById('tl-mode-live')?.addEventListener('click',()=>this.jumpHead());document.getElementById('tl-mode-asof')?.addEventListener('click',()=>this.setMode('asof'));document.getElementById('tl-mode-compare')?.addEventListener('click',()=>document.dispatchEvent(new CustomEvent('hera:navigate',{detail:'diff'})));document.getElementById('tl-mode-replay')?.addEventListener('click',()=>this.togglePlay());
    document.addEventListener('hera:route-changed',e=>{this.active=e.detail?.route==='time';if(!this.active)this.pause();});
    document.addEventListener('hera:stats',e=>{this.head=e.detail?.head??e.detail?.head_lsn??this.head;const el=document.getElementById('tl-head');if(el)el.textContent=`HEAD ${this.head??'—'}`;});
  },
  setMode(mode){document.querySelectorAll('.temporal-mode').forEach(b=>b.classList.remove('active'));document.getElementById(mode==='live'?'tl-mode-live':mode==='replay'?'tl-mode-replay':'tl-mode-asof')?.classList.add('active');},
  async load(){const n=document.getElementById('tl-notice');n.hidden=true;const r=await API.get('/security/events?limit=5000',{ms:30000});if(!r.ok){const e=explicarFalha(r.falha,r.estado);n.hidden=false;n.innerHTML=`<strong>Eventos indisponíveis.</strong> ${esc(e.longo)}`;this.setRows([]);return;}const d=r.dados;this.setRows(Array.isArray(d)?d:(d.events||d.items||[]));},
  setRows(rows){this.pause();this.rows=rows;this.entries=rows.map(row=>({row,time:toMs(rawTime(row)),lsn:Number(lsnOf(row))})).filter(x=>x.time!==null).sort((a,b)=>a.time-b.time||((Number.isFinite(a.lsn)?a.lsn:0)-(Number.isFinite(b.lsn)?b.lsn:0)));this.cursor=Math.max(0,this.entries.length-1);const slider=document.getElementById('tl-cursor');slider.max=String(Math.max(0,this.entries.length-1));slider.value=String(this.cursor);slider.disabled=!this.entries.length;document.getElementById('tl-count').textContent=`${this.entries.length.toLocaleString('pt-BR')} evento(s) datados · ${(rows.length-this.entries.length).toLocaleString('pt-BR')} sem data reconhecida`;this.calendar();this.paint();this.setMode('live');},
  calendar(){const c=document.getElementById('tl-calendar');c.replaceChildren();if(!this.entries.length){c.innerHTML='<div class="temporal-empty">Sem eventos datados para desenhar o mapa.</div>';return;}const last=this.entries.at(-1).time,end=new Date(last);end.setUTCHours(0,0,0,0);const start=new Date(end.getTime()-363*86400000);const counts=new Map();for(const e of this.entries){const k=dayKey(e.time);counts.set(k,(counts.get(k)||0)+1);}const max=Math.max(...counts.values(),1);for(let i=0;i<364;i++){const t=start.getTime()+i*86400000,k=dayKey(t),count=counts.get(k)||0,level=count?Math.max(1,Math.min(4,Math.ceil((count/max)*4))):0;const cell=document.createElement('button');cell.type='button';cell.className=`temporal-day level-${level}`;cell.dataset.day=k;cell.title=`${k}: ${count} evento(s)`;cell.setAttribute('aria-label',cell.title);cell.addEventListener('click',()=>this.jumpDay(k));c.append(cell);}},
  jumpDay(key){const index=this.entries.reduce((found,e,i)=>dayKey(e.time)===key?i:found,-1);if(index<0)return;this.pause();this.cursor=index;document.getElementById('tl-cursor').value=String(index);this.paint();this.setMode('asof');},
  jumpHead(){if(!this.entries.length)return;this.pause();this.cursor=this.entries.length-1;document.getElementById('tl-cursor').value=String(this.cursor);this.paint();this.setMode('live');},
  step(delta){if(!this.entries.length)return;this.pause();this.cursor=Math.max(0,Math.min(this.entries.length-1,this.cursor+delta));document.getElementById('tl-cursor').value=String(this.cursor);this.paint();this.setMode(this.cursor===this.entries.length-1?'live':'asof');},
  togglePlay(){if(this.timer){this.pause();return;}if(!this.entries.length)return;if(this.cursor>=this.entries.length-1)this.cursor=0;this.setMode('replay');const btn=document.getElementById('tl-play');btn.textContent='⏸';this.timer=setInterval(()=>{this.cursor=Math.min(this.entries.length-1,this.cursor+this.speed);document.getElementById('tl-cursor').value=String(this.cursor);this.paint();if(this.cursor>=this.entries.length-1){this.pause();this.setMode('live');}},180);},
  pause(){if(this.timer)clearInterval(this.timer);this.timer=null;const btn=document.getElementById('tl-play');if(btn)btn.textContent='▶';},
  paint(){const body=document.getElementById('tl-body'),lsnEl=document.getElementById('tl-cursor-lsn'),dateEl=document.getElementById('tl-cursor-date'),pe=document.getElementById('tl-progress-events'),pl=document.getElementById('tl-progress-lsn'),be=document.getElementById('tl-progress-events-bar'),bl=document.getElementById('tl-progress-lsn-bar');if(!this.entries.length){lsnEl.textContent='LSN —';dateEl.textContent='Sem eventos carregados';pe.textContent='0 / 0';pl.textContent='0%';be.style.width=bl.style.width='0%';body.innerHTML='<tr><td colspan="5" class="vazio">Nenhum dado carregado.</td></tr>';return;}const current=this.entries[this.cursor],first=this.entries[0],last=this.entries.at(-1),eventPct=((this.cursor+1)/this.entries.length)*100;let lsnPct=eventPct;if(Number.isFinite(first.lsn)&&Number.isFinite(last.lsn)&&last.lsn>first.lsn&&Number.isFinite(current.lsn))lsnPct=((current.lsn-first.lsn)/(last.lsn-first.lsn))*100;lsnEl.textContent=`LSN ${Number.isFinite(current.lsn)?current.lsn.toLocaleString('pt-BR'):'—'}`;dateEl.textContent=new Date(current.time).toISOString();pe.textContent=`${(this.cursor+1).toLocaleString('pt-BR')} / ${this.entries.length.toLocaleString('pt-BR')}`;pl.textContent=`${Math.max(0,Math.min(100,lsnPct)).toFixed(1)}%`;be.style.width=`${eventPct}%`;bl.style.width=`${Math.max(0,Math.min(100,lsnPct))}%`;
    document.querySelectorAll('.temporal-day').forEach(cell=>{const cutoff=dayKey(current.time);cell.classList.toggle('future',cell.dataset.day>cutoff);});
    const start=Math.max(0,this.cursor-199),slice=this.entries.slice(start,this.cursor+1);body.innerHTML=slice.reverse().map(({row,time})=>`<tr><td class="mono">${new Date(time).toISOString()}</td><td class="mono">${esc(lsnOf(row))}</td><td>${esc(row.source??row.datasource_id??row.agent_id)}</td><td>${esc(row.kind??row.category??row.activity??row.type)}</td><td><details><summary>JSON</summary><pre>${esc(JSON.stringify(row,null,2))}</pre></details></td></tr>`).join('');}
};
