import { API, explicarFalha } from '../api.js';
const esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rawTime=r=>r?.observed_at??r?.timestamp??r?.created_at??r?.time??r?.ts??r?.observed_at_unix_ms??r?.t_ms;
const toMs=v=>{if(typeof v==='string'){const n=Date.parse(v);return Number.isFinite(n)?n:null;}if(Number.isFinite(v)){if(v>1e17)return Math.floor(v/1e6);if(v>1e14)return Math.floor(v/1e3);if(v>1e11)return v;if(v>1e9)return v*1000;}return null;};
const lsnOf=r=>r?.lsn??r?.at_lsn??r?.last_seen_lsn??r?.integrity?.lsn??null;

export const TimeMachine={
  rows:[],entries:[],
  render(){return `<section id="time"><div class="secttl"><h2>Linha do Tempo</h2><span class="tag">dados reais · janela A/B</span></div>
    <p class="sub">Calendário de atividade baseado apenas em registros retornados pelo HeraclitusDB. Não são geradas portarias, valores ou eventos sintéticos quando a fonte está vazia.</p>
    <div id="tl-notice" class="aviso" hidden></div>
    <div class="card"><div class="toolbar"><button class="btn" id="tl-load">Carregar eventos</button><span class="pill b" id="tl-source">/security/events</span><span id="tl-count" class="muted">—</span></div>
      <div id="tl-calendar" class="calendar-grid" aria-label="Calendário de atividade"></div>
    </div>
    <div class="card"><h3>Janela temporal</h3><div class="dual-range"><label>A · início<input type="range" id="tl-a" min="0" max="0" value="0"></label><label>B · fim<input type="range" id="tl-b" min="0" max="0" value="0"></label></div><p id="tl-readout" class="timeline-readout">Sem dados.</p></div>
    <div class="card"><h3>Registros no recorte</h3><div class="table-wrap"><table><thead><tr><th>Data UTC</th><th>LSN</th><th>Fonte</th><th>Tipo</th><th>Evidência</th></tr></thead><tbody id="tl-body"><tr><td colspan="5" class="vazio">Nenhum dado carregado.</td></tr></tbody></table></div></div>
  </section>`},
  init(){document.getElementById('tl-load').onclick=()=>this.load();document.getElementById('tl-a').oninput=()=>this.paint('a');document.getElementById('tl-b').oninput=()=>this.paint('b');},
  async load(){const n=document.getElementById('tl-notice');n.hidden=true;const r=await API.get('/security/events?limit=1000',{ms:30000});if(!r.ok){const e=explicarFalha(r.falha,r.estado);n.hidden=false;n.innerHTML=`<strong>Eventos indisponíveis.</strong> ${esc(e.longo)}`;this.setRows([]);return;}const d=r.dados;const rows=Array.isArray(d)?d:(d.events||d.items||[]);this.setRows(rows);},
  setRows(rows){this.rows=rows;this.entries=rows.map(row=>({row,time:toMs(rawTime(row))})).filter(x=>x.time!==null).sort((a,b)=>a.time-b.time);document.getElementById('tl-count').textContent=`${this.entries.length} com data · ${rows.length-this.entries.length} sem data reconhecida`;const a=document.getElementById('tl-a'),b=document.getElementById('tl-b');const max=Math.max(0,this.entries.length-1);a.max=b.max=String(max);a.value='0';b.value=String(max);a.disabled=b.disabled=!this.entries.length;this.calendar();this.paint();},
  calendar(){const c=document.getElementById('tl-calendar');c.replaceChildren();if(!this.entries.length){c.textContent='Sem eventos datados para desenhar o calendário.';return;}const days=new Map();for(const e of this.entries){const k=new Date(e.time).toISOString().slice(0,10);days.set(k,(days.get(k)||0)+1);}const end=Math.floor(this.entries.at(-1).time/86400000)*86400000,start=Math.max(Math.floor(this.entries[0].time/86400000)*86400000,end-370*86400000);for(let t=start;t<=end;t+=86400000){const k=new Date(t).toISOString().slice(0,10),count=days.get(k)||0;const x=document.createElement('span');x.className=`calendar-day level-${Math.min(4,count)}`;x.title=`${k}: ${count} evento(s) na resposta`;x.setAttribute('aria-label',x.title);c.append(x);}},
  paint(changed){const a=document.getElementById('tl-a'),b=document.getElementById('tl-b'),body=document.getElementById('tl-body'),read=document.getElementById('tl-readout');if(!this.entries.length){read.textContent='Sem dados.';body.innerHTML='<tr><td colspan="5" class="vazio">Nenhum dado carregado.</td></tr>';return;}let i=Number(a.value),j=Number(b.value);if(i>j){if(changed==='a')j=i;else i=j;a.value=String(i);b.value=String(j);}const A=this.entries[i],B=this.entries[j];read.textContent=`A ${new Date(A.time).toISOString()} (LSN ${lsnOf(A.row)??'—'}) → B ${new Date(B.time).toISOString()} (LSN ${lsnOf(B.row)??'—'}) · ${j-i+1} registro(s)`;const slice=this.entries.slice(i,j+1);body.innerHTML=slice.map(({row,time})=>`<tr><td class="mono">${new Date(time).toISOString()}</td><td class="mono">${esc(lsnOf(row))}</td><td>${esc(row.source??row.datasource_id??row.agent_id)}</td><td>${esc(row.kind??row.category??row.activity??row.type)}</td><td><details><summary>JSON</summary><pre>${esc(JSON.stringify(row,null,2))}</pre></details></td></tr>`).join('');}
};
